export const filterCategories = [
  { id: 'beauty', name: 'Beauty' },
  { id: 'fragrances', name: 'Fragrances' },
  { id: 'furniture', name: 'Furniture' },
  { id: 'groceries', name: 'Groceries' },
  { id: 'kitchenAccessories', name: 'Kitchen Accessories' },
  { id: 'laptops', name: 'Laptops' },
  { id: 'mensShirts', name: 'Men’s Shirts' },
  { id: 'mensShoes', name: 'Men’s Shoes' },
  { id: 'mensWatches', name: 'Men’s Watches' },
  { id: 'mobileAccessories', name: 'Mobile Accessories' },
  { id: 'motorcycleGear', name: 'Motorcycle Gear' },
  { id: 'skinCare', name: 'Skin Care' },
  { id: 'smartphones', name: 'Smartphones' },
  { id: 'sportsAccessories', name: 'Sports Accessories' },
  { id: 'sunglasses', name: 'Sunglasses' },
  { id: 'tablets', name: 'Tablets' },
  { id: 'womensTops', name: 'Women’s Tops' },
  { id: 'vehicleAccessories', name: 'Vehicle Accessories' },
  { id: 'womensBags', name: 'Women’s Bags' },
  { id: 'womensDresses', name: 'Women’s Dresses' },
  { id: 'womensJewellery', name: 'Women’s Jewellery' },
  { id: 'womensShoes', name: 'Women’s Shoes' },
  { id: 'womensWatches', name: 'Women’s Watches' },
];
