export const filterCategories = [
  { id: 'beauty', name: 'Beauty' },
  { id: 'fragrances', name: 'Fragrances' },
  { id: 'furniture', name: 'Furniture' },
  { id: 'groceries', name: 'Groceries' },
  { id: 'kitchen-accessories', name: 'Kitchen' },
  { id: 'laptops', name: 'Laptops' },
  { id: 'mens-shirts', name: 'Men’s Shirts' },
  { id: 'mens-shoes', name: 'Men’s Shoes' },
  { id: 'mens-watches', name: 'Men’s Watches' },
  { id: 'mobile-accessories', name: 'Mobile Accessories' },
  { id: 'motorcycle-gear', name: 'Motorcycle Gear' },
  { id: 'skin-care', name: 'Skin Care' },
  { id: 'smartphones', name: 'Smartphones' },
  { id: 'sports-accessories', name: 'Sports Accessories' },
  { id: 'sunglasses', name: 'Sunglasses' },
  { id: 'tablets', name: 'Tablets' },
  { id: 'womens-tops', name: 'Women’s Tops' },
  { id: 'vehicle-accessories', name: 'Vehicle Accessories' },
  { id: 'womens-bags', name: 'Women’s Bags' },
  { id: 'womens-dresses', name: 'Women’s Dresses' },
  { id: 'womens-jewellery', name: 'Women’s Jewellery' },
  { id: 'womens-shoes', name: 'Women’s Shoes' },
  { id: 'womens-watches', name: 'Women’s Watches' },
]
